# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "bcF/ET9sZbqXtTe0kD4wZIYywWNXHqo1roscTbAH4k5fvIID2BUejaPin0C66M1YBKciC2DsoTLO3GLdUMEgCZCa51WdVvMA3dMaB0MQ3pCFOiwVymIp5pAMdaqGzGDMW/bAXdWDHm61NIFs8l5bW0msR4fodQ8TKLWa2TASS4VS0RNIL1LbcqPjqSF323xjiVVa1tHmb5p2tKR7uxoo1Jv04mdHVAJkqll7T2rCqIeJKj/57wttJjuQWO/FKu8/VvibnzkjQ4X+sIs1LP3t7V1KQCoRD38j/3XZk2sQ4+pJspUoJEkD9bpc8tlBdIXTSQRIyrcD84S5nq2o83mwqMBWC4j7MdOR0bcqnhAN74tKobKrgcRB26Mp5+qLGxpfUXIRQbtCXSMO95w1gfxEnPblKxUaR9t7Dg5+zP/yJ0uFJNF1kRWae5dXZXquoNSmrt0GyRIA1DyVqlsB/3nU5uN1TBUolz+4EkcQwH6/Ux2cFqKKtq9PkSoIHg4iKVvILAKJ81Pckpyx8aAnl+TD5zHrsQ5ugEFHGlHU73aBZHjiY17Kr2NYfwVHziGrCm1Zcp5HUy1eQyicDBZ4/zRYvGV9adKF7e3j1EPdBNciyk0666G+a28TJL+UdLIvHvODpP5gvCJzs/vUK4y13fs4a+Gcd8wezzGM/FXrd5CShR8="
    # AWS_SECRET_ACCESS_KEY
    - secure: "hvG4JFomCwDEMxUbpEstR0Tj0WIQccuPa0p07chbxCTU7lkWeFMZbeOMzrSv4JiES5cRcayzgyscy4GUL2sZqCpLpGZpmoREuwN480NO1XyHeMwylJ4D3xjdopQ5FWDmp+0w9lYEJVVk3apfiZh6n5Si8v+HhJn3wDSq7kokX69BKSX3njGjY+AQ9DOqLST5CMoc+f7NjwgduLQzyUUkEXUQHkXI9eA2ZeucuGgHHb0Gf4lbWCYt81HvKLCz0KghSmNJBNojZf2efjOf5b3RMkQ10RjmEV8ma4xZJMEjCaTlnAhJAM7/qwoCzEQDRvKnDm6+qQmRwK1BOa9MKIDy3z/mfAyjzyOeBpxKyxMEG/tYQnDyYfH0EF7e/5qfNu7hya3FANVIogujqIMFLpGtBkRexLCUIsgpjnXZdh6fFLEnq5ZBcA5gum9YQJzR0/1eqYw9F+WGFKMx0dQCfjcror4rfwvSGoHOLaT7/diMQZKVpMYosAzWjltOnGDaB9sqczE5kfl2/SLUDs8pD5breBaTzFqF5c1kv9oOKuLilaXtv+CoKRPObjEmmprjWUo6ucW3JryLiy71vcz82JVvTSoxbkYAtQYyBXeVes33NfXw5zX6shBNv1BU0C2T85wUtT51wetfwD7L3p+F7uIWMC39RkkvjI8LOMgec9b43F4="

# http://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.npm

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - openssl aes-256-cbc -K $encrypted_b48b31fc6699_key -iv $encrypted_b48b31fc6699_iv
    -in deploy/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  
install:
  - npm install -g bower-installer
  
script:
  - mvn clean install -B

before_deploy:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then echo "No deployment because branch is not master."; exit 0; fi
  - deploy/release.sh
  - ZIPFILE=`find target -name 'webapp-*.zip' -exec basename {} + | head -n 1`;
  - DATE=`date`;export ELASTIC_BEANSTALK_LABEL="${ZIPFILE//.zip/}_${DATE//[^a-zA-Z0-9]/_}";
  - echo "Version label is '$ELASTIC_BEANSTALK_LABEL'"
  
deploy:
  - provider: elasticbeanstalk
    edge: true
    skip_cleanup: true
    zip-file: target/$ZIPFILE
    region: eu-central-1
    app: wlc-webapp
    env: wlcwebapp
    bucket_name: wlc-webapp
    on:
      repo: welovecoding/webapp
      branch: master
