# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk8
  
# http://docs.travis-ci.com/user/build-lifecycle/  
before_install:
  - npm install -g bower  

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN

# http://docs.travis-ci.com/user/deployment/openshift/
deploy:
  provider: openshift
  user: bn@bennyn.de
  password:
    secure: hcYFpROsPJB0djTSJzO+QL5Qt27QwqAwEjUfJJmRdVZoJQ5L0J7PqDpBM+8JG4tPnnJo4+hlWOLCEw8AfxVjC+wD87FZy8pGrSQxAXDonYnfRzMtdI2YgSKYnKHv6/d862iRESLXkbP8PW6c347ZnZTCenI+cIIo5EVsSRlilXKBES1G9Vwg2vTqbqSRObFhZPwrvi717Beewdn0WM7WOlDpX78NGKRZzbZe/RFVf+6s2aIqVvdRSvVtRJex82S/yYJQsd1MaMBWN96hfmF0eJQEjxMML1i/nNfltb4w3IVY9qRHGs+vGxB9XNxk2iM3sCw6UDsOfKmdmgvozNKpU21H7LnVcZ6RuAhCH4n9j1Elo3OmzHql16rJUcPEYhbGqEjqqov7k9Kdkl0fZIpMAVzcZLiYfIpp8jZvsHihEJuJC1NHmQANlgac7WKFckIGyjsrWiujnTSYqwR8H3zvqHGObt+Pr7dteOkniX2tF/l3ZIsrxwW5d/8EUo4iVst++5RHz/1EH0txHo4/i4+LeP2xxw3wEjy2qvf3u0iObuVX/JjcUpbPvH2CdCcGVWOyZ9TO+lQtEPJhkvkddYwkiLWwoSXLOJ/Q39LjAd7ueesJ6c3lDwlhvl74afSZi46hiWrmUHc31N83N+CNw8zqkX7IzapM9i0Rj26zIUDTN3k=
  app: webapp
  domain: welovecoding
  on: master
  
env:
  global:
    # wlc.database.driver.classname
    - secure: If/pVvG1MAgsng3hBJnmiZ8++KdzwJUgK/XLsUtvVDhk9ktJsJauSP0lmrBkAoSP4xPAeWr2o8wqKxE8UVGwHck4gddDCIeVL1ANS0EUVKDvSon0FbCKS1WGzh/xadeQboYZhbiySjctzUvDTSbG3GVR91wozAFcSMxUotqdimsxmmi5GIVdrQHejTaD9e0Q+vqD2LED7suvaFZQ/DBDOEAMrkTxWKtW0R3ytqecEeABqdCVAomdT2o+IICyRytTBEbRiyumUH/+R5p7d7b3Mqyi1h5ybNd81j/Wer2bPGKQEF2h2/NobV94vPNyYnFUIP9XQxRwwmrJe46vLtADb3nvmlXbcywuCV3moXXz8+ulTUHaFocN9YYdO5G0L6/64UMMNTYyaxTsyrzyXhV/ewf4Bw78gcke8EIZiutvKWS3NZ2eEFG8JTrV5ObQdrO5aFFwge2IrOzI255k2oj0G1aa5gqJG9ueWnkkKBKFK+GlF3KDX25nHIcrUbpjgQ50Qcs2MF3GeqfL59yXPkX9yvr7FRQSELMD5p9Jqkw+wo3vz1bvLzbThJamBA+JFNWTJLtCf8crikJ15rQP396DH9Mjz9lJOYzNpo2Zb0wKbcSzIlVX3BRUgRlF4jcBmwPu62ZBgmRsTRy7pq8QU1mtp/J893d8qWs/VD8/cqr7NMQ=
    # wlc.database.url
    - secure: Q3Ps2XihRXPt75rrAYZYbeu7H3p+FQ1Jg/VhNNRXHFvLPC2kYH7EZUFxsl/eqOqoeTI5sC//Uv5FUMpXtyMrFgG0osyLO/3MU2QO5z4xD2cRyAWSrVQVmDbnvabeXyN6eA861tI8XvQFOoiLMHiKGHaeKU+iEStEYqsx5Adeff/4te4Q2RDx5Xcsk5Hyq2H3AbIQ9bXXSvcb9DKJjT2Cq6/yR93sZoGYliqQLzbj7p6h2RlWWmAUkxKFVbiXd6W0CXrUUQGoeMvTf+5iV2sr/1FpoRxKo/vbnhcJz489mP/musOJLlA7X8Bf/saHcvZj5negmBjmHDFVwV5c4JkbzLlgKmTy76LR3WoZg3PBtzW7cUNuW8vt2NkF3GCANqJrnd5+Numvg8e1GiamOoR/yA5gyqUZ6/Jnd8keYgzUAfA2/JezHeIvEqAbiuarziHICYAjsDRcERDNQaugXtIQGq73EoWz0gMEFD7MPmB3v/agDedXPyV99Duk18lz4rFlTwzOCcLYO2Z4wgc6jqrCGqB7m+8w1Rp/7R3zphxl9KkzqJ+vxg+mElPYBd44kckch1u9JbwrwZmJe9FCTkEFJT+sEv8sPmtmgLPsuCK8+KJj/2dvoxEpash4Gp5q6ajkqxhB3W5J0l7RtKgVTLDi0N0/8/lFEYatCzXb264QQZY=
    # wlc.database.username
    - secure: ITfDi8xkYjkS7aj+bD5ii/x5EU3W/kjvC7cCVAwJrcCoRxFdz9+2jVw3mNsGynDmcd1qOYw6OK+q6CFiuxDWyvEA0/Uhq6TUCXXh8BMkvX9AwB3nJGPFMNZikC2BaZ2IiidMz6quXXUydl4I/LKJmkPJ4ohlFRvAjVnuvUMLvh2zIJyBtzP2wF0RmGiOXMRx/yqIpbEDwP8t+wCc1lWG9AvGV2w1i8pCw6DDGRr+9IRjWevTbPKrEsqnaG2QRuwIbADUXiMcXCEd5edBrVKFhIZssXcO1zeR+drSgZnwkF6/ngR5Ddt8fRhWKeIwttwSmiA5Uc5rQbGDD5d/Coyi6Sr0LdQHEKiJNrlSgsb4tb01suBRezDhwcZkUS2gHtJ2AvGvdFJ+qib240mWwwQ6rtN+x85fHbTQW19B0IQuoW08rYW94cOUf5bbvCIegYwoG7MYvxF/Kd6Up8rdKIQyQGmRA3NMEDzvKbzegapKfnIUFSSveSkRdU4zXhmwyG2Yc9o2aMb4+BJGjkc85dqpHEb1lYJLOFe+wqdaK6lJuDietQqwYaeP0l2Q4droLZMIpNTz/GoqdwgEJicA+c8AHs15TVZtwDnSfdqLPZluuBCJ24f6raQ/XlSLZpTW5c9cSRqyPkO7NMTGx/Mpdagatzt5vQOL1ZpVNG9lk39PCYo=
    # wlc.database.password
    - secure: jPqVT/g5coVPFpMuiob3ZcmI0ur85CsPP/+VfWdgJ5Owrr4o1xW7+cNPRbMPh6xeLiIQx6OvE+SpnOq/jO/YvMyrOXx1yCN4dyTQ2xgcODlEaxRUBn8FY38nULd1AOvSNwCp6ZNGv94NOGudK8siRjBQjxr9hutO/MOcOPl4tt+8vyIZoGGxy6nJYj4JyQVqS0n0eB/iAxR/lX0E7eCCXia0M7bK+pR6LXR8Lz1apxiAbxDLDX0dlPliogq2Ygeim43zIbOeSLVgnlP0jfTHN/LFJDQuJQU9iyzgrZI6ya8RTvue1W0fe1cX1Sm7TyHPwv/BnPhu117xzQI1+RzC88EM3WVsoMTbR7t4EIBAtOJtIv4s8QRBPtDoDFBg+M57DH54BM5oOyYPXTiiedk03GUX+6zx/TfCtQ7+CcPpQjnlWKLHUzCuQFYhIF+G9KBdfaAUiAaDcRPYJwsXwNYxqK9twXSCdTzqA8QxoUmoCnHwb1gLbOcMuh/USm/rjPhO8jCJqA6kAGJnbuThXMzMHj4wWY9tUkXC6iEMsGe6umsvLmvYLr4hNT8aqD0uU+OMhWK4T9fIuMnBsKaFs/N/pis6azF9C/5dJ60Cksh461r2NcW+34o8/0/YCkU5YotnvW1M1GehYi41wW4bKEnOldKtx/Y8Wrw1gP2GJCG8wvk=
