# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - oraclejdk8

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - npm install -g bower

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN

#before_deploy:
#  - ls -la
#  - rm -rf src src pom.xml target .idea binary .editorconfig .gitattributes .gitignore .travis.yml README.md build_openshift_binary.sh nb-configuration.xml webapp.iml
#  - ls -la
#  - git -c "user.name=Travis" -c "user.email=travis@travis.org" commit -am "preparing deployment"


# http://docs.travis-ci.com/user/deployment/openshift/
deploy:
  provider: openshift
  skip_cleanup: true
  user: bn@bennyn.de
  password:
    secure: hcYFpROsPJB0djTSJzO+QL5Qt27QwqAwEjUfJJmRdVZoJQ5L0J7PqDpBM+8JG4tPnnJo4+hlWOLCEw8AfxVjC+wD87FZy8pGrSQxAXDonYnfRzMtdI2YgSKYnKHv6/d862iRESLXkbP8PW6c347ZnZTCenI+cIIo5EVsSRlilXKBES1G9Vwg2vTqbqSRObFhZPwrvi717Beewdn0WM7WOlDpX78NGKRZzbZe/RFVf+6s2aIqVvdRSvVtRJex82S/yYJQsd1MaMBWN96hfmF0eJQEjxMML1i/nNfltb4w3IVY9qRHGs+vGxB9XNxk2iM3sCw6UDsOfKmdmgvozNKpU21H7LnVcZ6RuAhCH4n9j1Elo3OmzHql16rJUcPEYhbGqEjqqov7k9Kdkl0fZIpMAVzcZLiYfIpp8jZvsHihEJuJC1NHmQANlgac7WKFckIGyjsrWiujnTSYqwR8H3zvqHGObt+Pr7dteOkniX2tF/l3ZIsrxwW5d/8EUo4iVst++5RHz/1EH0txHo4/i4+LeP2xxw3wEjy2qvf3u0iObuVX/JjcUpbPvH2CdCcGVWOyZ9TO+lQtEPJhkvkddYwkiLWwoSXLOJ/Q39LjAd7ueesJ6c3lDwlhvl74afSZi46hiWrmUHc31N83N+CNw8zqkX7IzapM9i0Rj26zIUDTN3k=
  app: wa
  domain: welovecoding
  on: master
