# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

env:
  global:
  # JDBC_DRIVER_CLASSNAME
  - secure: MZM1MukpL1nROvWEPucll6ls36Q36kP1r6eD4+bo0LmQTQrE9VBurSm5mMUP5fvuHBBgCONcvjiRZklY4eP1MuBnx0JAGCySxGlE+2UEMJeAtn5kKJxkqnvIcRCxPMG1LPeygMwWTUnXxo70lsUQHstv485wbmGLa/mOXvW3vORELY1z/1NxkHeNLJWS+ski0oYFUYz0TiGwPYzkW14v6qe18NXwU8lBJEwqSLhj7qQQLdjY7B3+QLOMj+xS875jctV+FozRMFTwzpACZNiVw06e9NWKqw5mQNJMglCs3nKVv2krNDitm3Oxaux2on7jTB8MGzT4qzaBQ2+5nVHRPNwbeOHkEMpm9M77yRuE6klAQhkPlSxRK4a8HJzaOqkU6mSWItTzjfc/P1HCAPFQnxXStwc9DH9i6zjSqqNXs+G8YS+gsgRE484LnpL1UkBKK11JvGvhp1BF2QCEf3utnzBC26kV215dA/2Ufp2piXKtz8r0AiaOCpR4QtEC0uqLX8nJtd+fY72YiV+v1mmD9/yAO6eI6JtB4HBfXYybl/zI/CmPp1SZd3BU2WOHnaBSNLoCGTDAZ6/BvUJpFhxHTWZ+w1EJ9KKo9Uq0nMc9CTlthBnx5z/UNzYLSDJMX5jvoXc+2/OATg2MkCE6sJLDu703D4g1I3nqhSP1jTAiKdM=
  # JDBC_URL
  - secure: ib5EH848cEJWM2E2nD8Kd7ExqDS1st6+AWdIA8URkDXrGMxcrzUftK0kgtDINBffYkgCfJS63R8OwEBMs9P9WjqeMXP51JuHGNQoo7k0HWjgMfLZNMgCgVqEgk7k5F5IM/2VpH/IadYehg05H8UVkflDZ4s1tcoI6i64soYmSEEqXMEP/gtnCq4kdq2QR33H9eRdN6cTxONB28lypxCmefSms/EJM9FynJY1yyh2Cj0LRlUtZkbhdl8I1XWEAyzB6oMC+nWyZ2llhHKiZO84WmRJSrpfocDPlSP6dLoYP64AGttcJOY3dLXBDExSN8i408q+HFdB3XVTa6CeGi+QAw0j3fRSybcokLYiE2oVkmQD3LXLXWOE61RHLSfyL+3nNXCaHPPtrncddLpxQNPNL3KCqhqctiDBJlwtdbWkbJZUR+d69mvBlwH6IRhFsvWzqGfqNPWixKP134DPt6byyli3PaXbY6ZSjtlRPBAV26RE/Y2kZEONzdqA2sOn48lBWPLTQUHO2flbImPcGaeUwkGytKpVNfsz7QHTZrr6R/bXRHVrpip1ZaPtMvmtW3sYfLhiVFnH1yNFzB3ZDh0DlvO8Tc2apPD4WNx/SVGUwm3L8yGQxURINclhxMup8prYH72l2BOj1r4/VxBaYZd9OsfBBSibJ+Byu8rV28za2SU=
  # DB_USERNAME
  - secure: Dm0jxJ+UgXnG+inOzGqbn/A8qomQtBxph0ru3V6i5u1UgwZ4xR6BGun/QiBJsmvbwrbLvyG2Gy6nBa03l9tIuYWEFfV/cUjZ1oMXxevvFTrnwsy5APhwAb5IzgA4S0GHRiT663TeaJnM+XQ0tdI8a001W6aqfAOyjr2oGEitt6a9SP/SBh4TDffnhG3ig4g6BVUAeS/NYF4Xdz/IgDHN2funoehhL4k+SPcDwI7QMQ/9mw7vakoQwXbPwLZ4K+FLqgji66SvW3zOVkhm1bSi6skHWp5jBVH4rFxhHUBmdtkKQi8TEWu2kxKGIs/2LobroaCo6kDJx8DtKLDNwtbg+7W5Xox7n2/LMbFWIpbSYPZ4+31nNp3UYdrxW1/0ETZprIid632N/Hk4Rcp9wQTdGumtDbwPctbAwk3LqlKnFHOh87Rx8CJnCuLftIBDKfm4i4zkKsWSAO2U6J1yvCRVxH4pFF4B1+7V41cY7ogwuJD6W8sM87g9RsLA/IBs5k3CyDOYPJ912O9JJyXDJvOYyhLtc2vIIYFcYf3gyp9yH8/20x4saVnDY459zZyvYKXFFQwyiuJCU44yimjemX/NQ6NjQXAcJGhNkrtnJf6pFgJVovvHmKG1lGeS2yHM7j34xWFAitTkmJlrQSNgKztTjXREkiMZXAJHRqLRq9euoM4=
  # DB_PASSWORD
  - secure: bggT9Yh+O4LgRRVrwLk0RObCkMx5Qs2Rkc68Xs4f7KmBS4cdhYx9y6nXWH1l30aQYzezBGS4b9XgMsCdCSH+xE5ZzOkPvMveWJH4LGtkKv9QfbfkDkpsFqxlKjAzBN6Tk7Ft6pE6SviS3Mkktna9QPi811SC2tSMXVFn3S/KPmJAncLpV5D7mHptGgLbSH/aVDvmMY1hJ6eUVpk/jIpyjb+IEuZVaIeSV2Wi6k9AWZHXrU8FVL578ZGvoKabwmd8psqo+xYRBatLs/SPk1XiZ4uLbGuLfOEYSiy/qRzZm9PdD7eLeRZnK9IyXvS6FCtYv3RQb3erR/srSaawWtDi+Cp+xIFKErU87m64qaxHUYuZMvj1QPhwhZZtu7QmlSg+RiJhd1GTjADrgNp4VyeA9n7J3FOIrqfKavM3GwEx1EHiwjeI0nVz0QHBakQTDWx3GULRSeixw9dNcgcTtrxJICgZsCrAfJaotd6q/NkqjHA8P3MPlL9/vbqTREVHxcy7yWlcAjg0WKsab9m173k5N+DGASbN0tQFwFO7hh6VpAvIgkUDAH36s/wxO5jNSUj6lQw0xpOb40FkzNyGkWuf6bDSLu26yiOFp16SOX7Wt36JOVNP5bGfg848ETB0+pMdVcjB5JN6NtDZoqZ+aRqcpYb8HVrNAAPTxJVmBvoplEE=  

# http://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk8
  
# http://docs.travis-ci.com/user/build-lifecycle/  
before_install:
  - npm install -g bower  
  
install:
  - mvn install -Popenshift -DskipTests=true -Dmaven.javadoc.skip=true -Dwlc.database.driver.classname=$JDBC_DRIVER_CLASSNAME -Dwlc.database.url=$JDBC_URL -Dwlc.database.username=$DB_USERNAME -Dwlc.database.password=$DB_PASSWORD -B -V

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN

# http://docs.travis-ci.com/user/deployment/openshift/
deploy:
  provider: openshift
  skip_cleanup: true  
  user: bn@bennyn.de
  password:
    secure: hcYFpROsPJB0djTSJzO+QL5Qt27QwqAwEjUfJJmRdVZoJQ5L0J7PqDpBM+8JG4tPnnJo4+hlWOLCEw8AfxVjC+wD87FZy8pGrSQxAXDonYnfRzMtdI2YgSKYnKHv6/d862iRESLXkbP8PW6c347ZnZTCenI+cIIo5EVsSRlilXKBES1G9Vwg2vTqbqSRObFhZPwrvi717Beewdn0WM7WOlDpX78NGKRZzbZe/RFVf+6s2aIqVvdRSvVtRJex82S/yYJQsd1MaMBWN96hfmF0eJQEjxMML1i/nNfltb4w3IVY9qRHGs+vGxB9XNxk2iM3sCw6UDsOfKmdmgvozNKpU21H7LnVcZ6RuAhCH4n9j1Elo3OmzHql16rJUcPEYhbGqEjqqov7k9Kdkl0fZIpMAVzcZLiYfIpp8jZvsHihEJuJC1NHmQANlgac7WKFckIGyjsrWiujnTSYqwR8H3zvqHGObt+Pr7dteOkniX2tF/l3ZIsrxwW5d/8EUo4iVst++5RHz/1EH0txHo4/i4+LeP2xxw3wEjy2qvf3u0iObuVX/JjcUpbPvH2CdCcGVWOyZ9TO+lQtEPJhkvkddYwkiLWwoSXLOJ/Q39LjAd7ueesJ6c3lDwlhvl74afSZi46hiWrmUHc31N83N+CNw8zqkX7IzapM9i0Rj26zIUDTN3k=
  app: webapp
  domain: welovecoding
  on: master
