spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: placeholder
    username: placeholder
    password: placeholder
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  mail:
    host: @wlc.mail.host@
    port: @wlc.mail.port@
    user: noreply@welovecoding.com
    password: @wlc.mail.password@
    protocol: smtp
    tls: false
    auth: true
  thymeleaf:
    cache: true

server:
  port: 8080
  http.cache: 
    ttl: 1 # days; custom value used in CachingHttpHeadersFilter
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json

# ===================================================================
# WeLoveCoding specific properties
# ===================================================================

wlc:
  google:
    projectId: we-love-coding
  metrics:
    jmx.enabled: true
    graphite:
      enabled: false
      host: localhost
      port: 2003
      prefix: wlc